FROM node:alpine3.20

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Build arguments
ARG NEXT_PUBLIC_SERVER_HOST
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_AWS_S3_REGION
ARG NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID
ARG NEXT_PUBLIC_AWS_S3_SECRET_KEY
ARG NEXT_PUBLIC_AWS_S3_SECRET_NAME
ARG NEXT_PUBLIC_AWS_S3_BUCKET_NAME
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_CLIENT_URL
ARG NEXT_PUBLIC_ZEGO_APPID
ARG NEXT_PUBLIC_SERVER_SECRET

# Set environment variables
ENV NEXT_PUBLIC_SERVER_HOST=$NEXT_PUBLIC_SERVER_HOST
ENV GOOGLE_ID=$GOOGLE_ID
ENV GOOGLE_SECRET=$GOOGLE_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_AWS_S3_REGION=$NEXT_PUBLIC_AWS_S3_REGION
ENV NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID=$NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID
ENV NEXT_PUBLIC_AWS_S3_SECRET_KEY=$NEXT_PUBLIC_AWS_S3_SECRET_KEY
ENV NEXT_PUBLIC_AWS_S3_SECRET_NAME=$NEXT_PUBLIC_AWS_S3_SECRET_NAME
ENV NEXT_PUBLIC_AWS_S3_BUCKET_NAME=$NEXT_PUBLIC_AWS_S3_BUCKET_NAME
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLIENT_URL=$NEXT_PUBLIC_CLIENT_URL
ENV NEXT_PUBLIC_ZEGO_APPID=$NEXT_PUBLIC_ZEGO_APPID
ENV NEXT_PUBLIC_SERVER_SECRET=$NEXT_PUBLIC_SERVER_SECRET

RUN npm run build

EXPOSE 3000

CMD [ "npm","run","start" ]