import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StoreProvider from "./StoreProvider";
import { NextAuthProvider } from "./SessionProvider";
import { usePathname, useRouter } from "next/navigation";
import { headers } from "next/headers";
import AdminLayout from "@/components/Layout/AdminLayout";
import UserLayout from "@/components/Layout/UserLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bidder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = headers();
  const isAdminRoute = header.get("x-url")?.startsWith("/admin");

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NextAuthProvider>
            {isAdminRoute ? (
              <main>{children}</main>
            ) : (
              <UserLayout>{children}</UserLayout>
            )}
          </NextAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
