name: Deploy Bidder Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t hunais/bidder-frontend .
      - name: Push to docker image
        run: docker push hunais/bidder-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pulling image
        run: docker pull hunais/bidder-frontend:latest
      - name: Stop existing container
        run: docker stop hunais/bidder-frontend || true
      - name: Deleting existing container
        run: docker rm bidder-frontend || true
      - name: Run docker container
        run: |
          docker run -d -p 3000:3000 --name bidder-frontend \
            -e NEXT_PUBLIC_SERVER_HOST="${{ secrets.NEXT_PUBLIC_SERVER_HOST }}" \
            -e GOOGLE_ID="${{ secrets.GOOGLE_ID }}" \
            -e GOOGLE_SECRET="${{ secrets.GOOGLE_SECRET }}" \
            -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            -e NEXT_PUBLIC_AWS_S3_REGION="${{ secrets.NEXT_PUBLIC_AWS_S3_REGION }}" \
            -e NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID="${{ secrets.NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID }}" \
            -e NEXT_PUBLIC_AWS_S3_SECRET_KEY="${{ secrets.NEXT_PUBLIC_AWS_S3_SECRET_KEY }}" \
            -e NEXT_PUBLIC_AWS_S3_SECRET_NAME="${{ secrets.NEXT_PUBLIC_AWS_S3_SECRET_NAME }}" \
            -e NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" \
            -e NEXT_PUBLIC_CLIENT_URL="${{ secrets.NEXT_PUBLIC_CLIENT_URL }}" \
            -e NEXT_PUBLIC_ZEGO_APPID="${{ secrets.NEXT_PUBLIC_ZEGO_APPID }}" \
            -e NEXT_PUBLIC_SERVER_SECRET="${{ secrets.NEXT_PUBLIC_SERVER_SECRET }}" \
            hunais/bidder-frontend:latest